### PR TITLE
Add logger support

### LINKED ISSUE #80: Remove console.log
- Remove all console.logs from the code.

### PR DESCRIPTION
**Pull request by sarvesh-ost**
Fixes #80  

This PR does the following things: 
1. Added logger class, which enables logging on the console or to a file based following environment variable. 
2. Added support of log levels.
3. Removed console log. 

1. Logging to a file can be enabled by setting `ENABLE_BRANDED_TOKEN_JS_LOGGER` environment variable to `true`. 

```
export ENABLE_BRANDED_TOKEN_JS_LOGGER=true

```

2. `BRANDED_TOKEN_JS_LOGGER_PATH` environment variable can be set to specify the directory of the log file. Default value is `${currentDirectory}/log`
```
export BRANDED_TOKEN_JS_LOGGER_PATH=/path
```
3. Default log level is `info`, it can be changed by updating the enviornment variable. 
```
export LOG_LEVEL=error

```

### CODE REVIEW

**Comment by rachinkapoor** [comment]
Hi @sarvesh-ost, @deepesh-kn , @abhayks1 
While console.log could be removed, but, logs should be present in one or the other form.
Removing logs all together (as in this PR) would mean, devs will have zero info and will need to change the NPM module code to debug further.

**Comment by deepesh-kn** [comment]
> Hi @sarvesh-ost, @deepesh-kn , @abhayks1
> While console.log could be removed, but, logs should be present in one or the other form.
> Removing logs all together (as in this PR) would mean, devs will have zero info and will need to change the NPM module code to debug further.

Is there any specific location you need logs? We can add a proper loggers to print the receipts and transaction hash.

**Comment by rachinkapoor** [comment]
IMHO, we should log everything. It should be filtered by verbosity or log level.
When things don't work out, these logs are very helpful.

Few things that we should log:
- What tx are we executing
- The tx hash
- The tx receipt 
- Any errors.

**Comment by schemar** [comment]
@sarvesh-ost I think instead of simply *removing* all logging we should agree on a logging library cross-repository and implement that everywhere. See also https://github.com/OpenSTFoundation/mosaic.js/issues/49

**Comment by sarvesh-ost** [comment]
> @sarvesh-ost I think instead of simply _removing_ all logging we should agree on a logging library cross-repository and implement that everywhere. See also [OpenSTFoundation/mosaic.js#49](https://github.com/OpenSTFoundation/mosaic.js/issues/49)

Agree, [Winson](https://github.com/winstonjs/winston) seems like a good option.

**Comment by schemar** [comment]
> 
> 
> > @sarvesh-ost I think instead of simply _removing_ all logging we should agree on a logging library cross-repository and implement that everywhere. See also [OpenSTFoundation/mosaic.js#49](https://github.com/OpenSTFoundation/mosaic.js/issues/49)
> 
> Agree, [Winston](https://github.com/winstonjs/winston) seems like a good option.

https://github.com/OpenST/developer-guidelines/issues/2

**Comment by schemar** [comment]
@sarvesh-ost should we re-formulate the ticket and then you can update the PR to replace `console.log()` with a logging library?

**Comment by benjaminbollen** [comment]
I ll consider this paused; but let's remove `console.log` and put in logger before 4th march; @schemar can you create ticket?

**Comment by schemar** [comment]
> I ll consider this paused; but let's remove `console.log` and put in logger before 4th march; @schemar can you create ticket?

I created #107 @benjaminbollen @sarvesh-ost 
Please note that it must be done **this week.**

**Comment by sarvesh-ost** [comment]
> Looks ok 👌
> 
> Two main comments:
> 
> 1. the library should most likely **not** log to a file, rather command line only
> 2. there is a lot of repeated "log then return error"
> 
> * either create a new error (e.g. `LoggedTypeError`) which combines logging and is the error
> * or think about whether logging an exception is valuable in the first place, as it will always be returned as an error to the consumer and the consumer can decide what to do with it
> 
> Bonus question: any ideas yet how to toggle the logger as a consumer?

1. With this PR, library logs on the console by default and logging to file can be enabled by setting an environment variable. 

2. I am not in favor of encapsulating logger statement and throwing an exception into a single unit. 
Having an explicit log an exception is more readable in my opinion.

**Comment by schemar** [comment]
> > Looks ok 👌
> > Two main comments:
> > 
> > 1. the library should most likely **not** log to a file, rather command line only
> > 2. there is a lot of repeated "log then return error"
> > 
> > 
> > * either create a new error (e.g. `LoggedTypeError`) which combines logging and is the error
> > * or think about whether logging an exception is valuable in the first place, as it will always be returned as an error to the consumer and the consumer can decide what to do with it
> > 
> > Bonus question: any ideas yet how to toggle the logger as a consumer?
> 
>     1. With this PR, library logs on the console by default and logging to file can be enabled by setting an environment variable.

Nice 👍 

>     2. I am not in favor of encapsulating logger statement and throwing an exception into a single unit.
>        Having an explicit log an exception is more readable in my opinion.

You are not in favor of encapsulation and would rather write everything in a single function top to bottom (the [John Carmack way](http://number-none.com/blow/john_carmack_on_inlined_code.html))?

**Comment by sarvesh-ost** [comment]
> > > Looks ok 👌
> > > Two main comments:
> > > 
> > > 1. the library should most likely **not** log to a file, rather command line only
> > > 2. there is a lot of repeated "log then return error"
> > > 
> > > 
> > > * either create a new error (e.g. `LoggedTypeError`) which combines logging and is the error
> > > * or think about whether logging an exception is valuable in the first place, as it will always be returned as an error to the consumer and the consumer can decide what to do with it
> > > 
> > > Bonus question: any ideas yet how to toggle the logger as a consumer?
> > 
> > 
> > ```
> > 1. With this PR, library logs on the console by default and logging to file can be enabled by setting an environment variable.
> > ```
> 
> Nice 👍
> 
> > ```
> > 2. I am not in favor of encapsulating logger statement and throwing an exception into a single unit.
> >    Having an explicit log an exception is more readable in my opinion.
> > ```
> 
> You are not in favor of encapsulation and would rather write everything in a single function top to bottom (the [John Carmack way](http://number-none.com/blow/john_carmack_on_inlined_code.html))? (including also code duplication?)

It's not true that I am not in favor of encapsulation.  
From my understanding logging, a statement and throwing an error are two different things.  They shouldn't be encapsulated into one.

**Comment by schemar** [comment]
I mean ... the [John Carmack way](http://number-none.com/blow/john_carmack_on_inlined_code.html) definitely has its merits. Depending on the situation, I think both approaches are absolutely viable.

Maybe another way would be a method on the class that logs and throws. `this.throwLogged(message: string)` or something?

**Pull request merged**
